app:
  # how many rows one langCalcNode will process
  step: 100

  # decide to run which input file, 0-tiny, 1-small, 2-big
  input-twitter-type: 1-

  # important file paths
  grid-path: E:\projects\COMP90024_Assignment_1\sample\sydGrid.json
  tiny-twitter-path: E:\projects\COMP90024_Assignment_1\sample\tinyTwitter.json
  small-twitter-path: E:\projects\COMP90024_Assignment_1\sample\smallTwitter.json
  big-twitter-path: E:\projects\COMP90024_Assignment_1\sample\bigTwitter.json

  # grid matrix information
  grid-rows: 4
  grid-columns: 4

  thread-pool:
    size: 2
